# Builder
FROM    golang:latest as BUILDER
RUN     mkdir -p /go/src/github.com/tchaudhry91/cloudinventory
ENV     GO111MODULE=on
WORKDIR /go/src/github.com/tchaudhry91/cloudinventory
COPY    . .
ENV     CGO_ENABLED=0
ENV     GOOS=linux
ENV     GOARCH=arm
RUN     go get
RUN     go build

# Final Image
FROM       hypriot/rpi-alpine
RUN        apk update && apk add --no-cache ca-certificates
COPY       --from=BUILDER /go/src/github.com/tchaudhry91/cloudinventory/cloudinventory /bin/
ENTRYPOINT [ "/bin/cloudinventory" ]
